
/*
    This is a dimension table which has location specific details
*/

{{ config(materialized='table') }}

WITH SOURCE_DATA AS (

    SELECT DISTINCT
    LOCATION,
	TIME_ZONE,
	TOTAL_RURAL_VILLAGES,
	LATITUDE,
	LOCATION_ISO_CODE,
	TOTAL_REGENCIES,
	POPULATION_DENSITY,
	POPULATION,
	TOTAL_CITIES,
	TOTAL_DISTRICTS,
	ISLAND,
	LONGITUDE,
	PROVINCE,
	SPECIAL_STATUS,
	CONTINENT,
	TOTAL_URBAN_VILLAGES,
	COUNTRY,
	LOCATION_LEVEL,
	AREA_KM_2_ AS AREA_IN_KM2
    FROM "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_ABINAYA_SUBBIAH"

)

SELECT ROW_NUMBER() OVER (ORDER BY LOCATION) AS LOCATION_DETAILS_ID, SOURCE_DATA.*
FROM SOURCE_DATA


