
version: 2

models:
    - name: location_details
      description: "This is a dimension table which has location details"
    #   columns:
    #       - name: location_details_id
    #         description: "The primary key for this table"
    #         tests:
    #             - unique
    #             - not_null

    - name: active_cases
      description: "Fact table for active and total cases"
    #   columns:
    #       - name: date
    #         description: "The primary key for this table"
    #         tests:
    #             - unique
    #             - not_null

    - name: death_recovery_details
      description: "Fact table for death and recovery details"
    #   columns:
    #       - name: date
    #         description: "The primary key for this table"
    #         tests:
    #             - unique
    #             - not_null

    - name: cumulative_statistics
      description: "View which shows cumulative statistics"
